version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ifpracesso
    ports:
      - "5432:5432"
    networks: 
      - main
  web:
    build: .
    command: ./run.sh
    volumes:
      - .:/webapps
    ports:
      - "8000:8000"
    networks: 
      - main
networks: 
  main: